Ttree:
  Oembed:
    resource:
      classNamePattern: 'Ttree\Oembed\Resource\@type'
      postProcessors:
        youtube: 'Ttree\Oembed\Resource\PostProcessor\YoutubePostProcessor'

Neos:
  Neos:
    fusion:
      autoInclude:
        'Ttree.Oembed': TRUE